package keycloaklib

const (
	emptyString = ""
)
const (
	ErrConfigRequired                           = "config is required"
	ErrKeycloakURLRequired                      = "KEYCLOAK_URL variable is required"
	ErrKeycloakRealmRequired                    = "KEYCLOAK_REALM variable is required"
	ErrKeycloakClientIDRequired                 = "KEYCLOAK_CLIENT_ID variable is required"
	ErrKeycloakClientSecretRequired             = "KEYCLOAK_CLIENT_SECRET variable is required"
	ErrClientIDAndSecretRequired                = "client_id and client_secret are required for admin operations"
	ErrNoAccessToken                            = "no access token in response"
	ErrNoRefreshToken                           = "no refresh token available"
	ErrNoAccessTokenInRefresh                   = "no access token in refresh response"
	ErrTokenRefreshFailed                       = "token refresh failed: %w"
	ErrFailedToCreateRequest                    = "failed to create request: %w"
	ErrFailedToExecuteRequest                   = "failed to execute request: %w"
	ErrFailedToReadResponse                     = "failed to read response: %w"
	ErrFailedToGetToken                         = "failed to get token: %d %s"
	ErrFailedToRefreshToken                     = "failed to refresh token: %d %s"
	ErrFailedToParseToken                       = "failed to parse token response: %w"
	ErrFailedToMarshalUser                      = "failed to marshal user data: %w"
	ErrFailedToCreateUserRequest                = "failed to create user request: %w"
	ErrFailedToCreateUser                       = "failed to create user: %d %s"
	ErrNoLocationHeader                         = "no Location header in response"
	ErrInvalidLocationHeader                    = "invalid Location header"
	ErrFailedToGetUserRequest                   = "failed to create get user request: %w"
	ErrFailedToExecuteGetUser                   = "failed to execute get user request: %w"
	ErrFailedToGetUser                          = "failed to get user: %d %s"
	ErrFailedToDecodeUser                       = "failed to decode user response: %w"
	ErrFailedToDeleteUserRequest                = "failed to create delete user request: %w"
	ErrFailedToExecuteDeleteUser                = "failed to execute delete user request: %w"
	ErrFailedToDeleteUser                       = "failed to delete user: %d %s"
	ErrUsernamePasswordRequired                 = "username and password are required"
	ErrClientIDRequired                         = "client_id or other_client_id is required"
	ErrFailedToObtainLoginToken                 = "failed to obtain login token: status %d, body: %s"
	ErrFailedToCreateGetClientRequest           = "failed to create get client request: %w"
	ErrFailedToExecuteGetClient                 = "failed to execute get client request: %w"
	ErrFailedToGetClient                        = "failed to get client, status: %d, body: %s"
	ErrFailedToDecodeClients                    = "failed to decode clients: %w"
	ErrNoClientFound                            = "no client found with clientId: %s"
	ErrFailedToCreateGetClientRoleRequest       = "failed to create get client role request: %w"
	ErrFailedToExecuteGetClientRole             = "failed to execute get client role request: %w"
	ErrFailedToGetClientRole                    = "failed to get client role, status: %d, body: %s"
	ErrFailedToDecodeClientRole                 = "failed to decode client role: %w"
	ErrFailedToGetClientWrapper                 = "failed to get client: %w"
	ErrFailedToGetClientRoleWrapper             = "failed to get client role %s: %w"
	ErrFailedToMarshalClientRoles               = "failed to marshal client roles: %w"
	ErrFailedToCreateAddClientRolesRequest      = "failed to create add client roles request: %w"
	ErrFailedToExecuteAddClientRoles            = "failed to execute add client roles request: %w"
	ErrFailedToAddClientRoles                   = "failed to add client roles, status: %d, body: %s"
	ErrUsernameAndEmailRequired                 = "username and email are required"
	ErrUserIDRequired                           = "userID is required"
	ErrFailedToCreateResetPasswordEmailRequest  = "failed to create reset password email request: %w"
	ErrFailedToExecuteResetPasswordEmailRequest = "failed to execute reset password email request: %w"
	ErrFailedToTriggerPasswordResetEmail        = "failed to trigger password reset email: status %d, body %s"
	ErrUsernameRequired                         = "username is required"
	ErrNoUserFound                              = "no user found with username: %s"
	ErrMultipleUsersFound                       = "multiple users found with username: %s"
	ErrFailedToCreateGetUserRequest             = "failed to create get user request: %w"
)
